name: commitlint

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR Title (Semantic)
    runs-on: ubuntu-latest
    steps:
      - name: Semantic Pull Request Check
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 是否校验 PR 的标题（推荐，因为 Squash Merge 时会用到）
          validateSingleCommit: false
          # 如果你想严格检查 PR 里的每一个 commit，可以启用以下配置：
          # ignoreCommitsWithSubject: '^(Merge |Revert )'
